apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sber-monitoring
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Stalker1301981-alt/sber-monitoring.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kovaliov2700-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
