apiVersion: apps/v1
kind: Deployment
metadata:
  name: sber-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sber-monitoring
  template:
    metadata:
      labels:
        app: sber-monitoring
    spec:
      containers:
      - name: app
        image: python:3.9-slim
        ports:
        - containerPort: 8080
        command: ["python3", "calc.py"]
        env:
        - name: DRUID_HOST
          value: druid-broker.infra.svc.cluster.local
        - name: DRUID_PORT
          value: "8082"
        - name: APP_VERSION
          value: "2.0"
