apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sber-monitoring-manual
  namespace: kovaliov2700-dev
  labels:
    app: sber-monitoring
spec:
  host: sber-monitoring-manual-kovaliov2700-dev.apps.rm3.7wse.p1.openshiftapps.com
  to:
    kind: Service
    name: sber-monitoring
    weight: 100
  port:
    targetPort: 3000 # Явно указываем числовой порт вашего калькулятора
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
