apiVersion: v1
kind: Service
metadata:
  name: sber-monitoring
  namespace: art2010901-dev
  labels:
    app: sber-monitoring-prod
spec:
  selector:
    app: sber-monitoring-prod
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 8000
    targetPort: 8000
  type: ClusterIP
