apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sber-monitoring
  namespace: art2010901-dev
  labels:
    app: sber-monitoring
spec:
  selector:
    matchLabels:
      app: sber-monitoring-prod
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
  namespaceSelector:
    matchNames:
    - art2010901-dev
